### ISSUE TITLE
декомпозировать компонент на составляющие его компоненты

### ISSUE THREAD

**Issue by apankov** [krauchuk/travel-assistant#1]
https://github.com/krauchuk/travel-assistant/blob/499181d25d60f21727b1bee0d8ab99013209a641/src/containers/city.jsx#L41

этот метод `render` совершенно никуда не годится
- такое чувство что здесь рендерятся несколько разных видов "городов"
- тернарных операторов слишком много
- код метода не читабельный

необходимо разделить компонент на несколько других компонентов, более подходящих по смыслу.

**Comment by krauchuk** [comment]
Переписал контейнеры
